### ISSUE TITLE
결재수단 선택페이지 UI 작성

### ISSUE THREAD

**Issue by sc2bat** [sc2bat/griffin_flight#11]

**Comment by ALSDlab** [comment]
bootpay 패키지 연동
결제수단 선택 - 카드결제, 계좌이체, 휴대폰소액결제 
결제금액 표

**Comment by ALSDlab** [comment]
Use case 정의 - repository 에서 price, order_name, order_id 파라메터 정보를 받아서 bootpay 일반결제 구현

**Comment by ALSDlab** [comment]
https://pub.dev/packages/ticket_widget 패키지로 비행기 티켓 형태 구현
