### ISSUE TITLE
결재정보 입력/완료 페이지 UI 작성

### ISSUE THREAD

**Issue by sc2bat** [sc2bat/griffin_flight#14]

**Comment by ALSDlab** [comment]
카드번호, 만료년월, CVC번호, 비밀번호, 이름 등 정보 입력 - 검증여부
은행선택, 계좌번호, 이름 입력
핸드폰 번호, 이름 입력 - 검증여부

**Comment by ALSDlab** [comment]
Use Case 정의 - bootpay에서 처리하므로 별도 필요 없음
