### ISSUE TITLE
[reserve_page] Feature

### ISSUE THREAD

**Issue by sc2bat** [sc2bat/griffin_flight#16]

**Comment by AngieEJJ** [comment]
Flight Details Page
1. 조회 페이지에서 저장된 데이터 가져오기 
2. 조회 페이지에서 인원 수 체크 

Traveller Details Page
1. 정보 저장되어 예약정보 최종확인 페이지로 뿌리기
2. Total Fare 가져오기

Seats Selection Page
1. 선택한 정보 예약정보 최종확인 페이지로 뿌리기
